project:
  group: laplacian-arch
  name: service-api.domain-model
  type: domain-model
  namespace: laplacian.arch.service.api
  version: '1.0.0'
  description:
    en: |
      A model that expresses the logical structure of a service API.
      This model consists of REST api model, GraphQL interface model, and datasource usage model.
    ja: |
      A model that expresses the logical structure of a service API.
      This model consists of REST api model, GraphQL interface model, and datasource usage model.
    zh: |
      A model that expresses the logical structure of a service API.
      This model consists of REST api model, GraphQL interface model, and datasource usage model.
  source_repository:
    url: https://github.com/laplacian-arch/laplacian-arch.service-api.domain-model.git
    branch: master
  module_repositories:
    local:
      ../../../mvn-repo
    remote:
    - https://github.com/nabla-squared/mvn-repo
  models:
  - group: laplacian-arch
    name: datasource.domain-model
    version: '1.0.0'
  model_files:
  - 'src/'
