@startuml
left to right direction


class ApiCallArgument [[/blob/master/doc/entities/ApiCallArgument.md]] {
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/ApiCallArgument.md#name-string name]]: <color:GRAY>String</color>
  <color:Green><&star></color>[[/blob/master/doc/entities/ApiCallArgument.md#type-string type]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/ApiCallArgument.md#description-string description]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/ApiCallArgument.md#required-boolean required]]: <color:GRAY>Boolean</color>
  [[/blob/master/doc/entities/ApiCallArgument.md#multiple-boolean multiple]]: <color:GRAY>Boolean</color>
  [[/blob/master/doc/entities/ApiCallArgument.md#nullable-boolean nullable]](): <color:GRAY>Boolean</color>
  [[/blob/master/doc/entities/ApiCallArgument.md#default_value-string default_value]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/ApiCallArgument.md#class_name-string className]](): <color:GRAY>String</color>
  [[/blob/master/doc/entities/ApiCallArgument.md#graphql_type-string graphqlType]](): <color:GRAY>String</color>
}




class CachePolicy [[/blob/master/doc/entities/CachePolicy.md]] {
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/CachePolicy.md#name-string name]]: <color:GRAY>String</color>
  <color:RED><&flag></color><color:Green><&star></color>[[/blob/master/doc/entities/CachePolicy.md#store_type-string store_type]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/CachePolicy.md#ignore_error-boolean ignore_error]]: <color:GRAY>Boolean</color>
  [[/blob/master/doc/entities/CachePolicy.md#key-string key]](): <color:GRAY>String</color>
}





package laplacian.arch.api.service {
  class Duration {
  }
}


CachePolicy *-- "0..1" Duration : expiration_time





package laplacian.arch.api.service {
  class ConfigurationBinding {
  }
}


CachePolicy *-- "*" ConfigurationBinding : configurations




class HeapMemoryCachePolicy [[/blob/master/doc/entities/HeapMemoryCachePolicy.md]] {
}

HeapMemoryCachePolicy --|> CachePolicy





class RedisCachePolicy [[/blob/master/doc/entities/RedisCachePolicy.md]] {
}

RedisCachePolicy --|> CachePolicy





class Duration [[/blob/master/doc/entities/Duration.md]] {
  <color:Green><&star></color>[[/blob/master/doc/entities/Duration.md#amount-string amount]]: <color:GRAY>String</color>
  <color:Green><&star></color>[[/blob/master/doc/entities/Duration.md#unit-string unit]]: <color:GRAY>String</color>
}




class AvgBucketAggregate [[/blob/master/doc/entities/AvgBucketAggregate.md]] {
  <color:Green><&star></color>[[/blob/master/doc/entities/AvgBucketAggregate.md#buckets_path-string buckets_path]]: <color:GRAY>String</color>
}

AvgBucketAggregate --|> ElasticsearchAggregate





class BucketScriptAggregate [[/blob/master/doc/entities/BucketScriptAggregate.md]] {
  <color:Green><&star></color>[[/blob/master/doc/entities/BucketScriptAggregate.md#script-string script]]: <color:GRAY>String</color>
}

BucketScriptAggregate --|> ElasticsearchAggregate







BucketScriptAggregate *-- "1..*" BucketScriptPath : buckets_path




class BucketScriptPath [[/blob/master/doc/entities/BucketScriptPath.md]] {
  <color:Green><&star></color>[[/blob/master/doc/entities/BucketScriptPath.md#name-string name]]: <color:GRAY>String</color>
  <color:Green><&star></color>[[/blob/master/doc/entities/BucketScriptPath.md#path-string path]]: <color:GRAY>String</color>
}




class BucketSelectorAggregate [[/blob/master/doc/entities/BucketSelectorAggregate.md]] {
  <color:Green><&star></color>[[/blob/master/doc/entities/BucketSelectorAggregate.md#script-string script]]: <color:GRAY>String</color>
}

BucketSelectorAggregate --|> ElasticsearchAggregate







BucketSelectorAggregate *-- "1..*" BucketScriptPath : buckets_path




class BucketSortAggregate [[/blob/master/doc/entities/BucketSortAggregate.md]] {
  [[/blob/master/doc/entities/BucketSortAggregate.md#from-string from]]: <color:GRAY>String?</color>
  [[/blob/master/doc/entities/BucketSortAggregate.md#variable_from-boolean variableFrom]](): <color:GRAY>Boolean</color>
  [[/blob/master/doc/entities/BucketSortAggregate.md#bucket_size-string bucket_size]]: <color:GRAY>String?</color>
  [[/blob/master/doc/entities/BucketSortAggregate.md#variable_bucket_size-boolean variableBucketSize]](): <color:GRAY>Boolean</color>
}

BucketSortAggregate --|> ElasticsearchAggregate






package laplacian.arch.api.service.elasticsearch {
  class FieldSort {
  }
}


BucketSortAggregate *-- "1..*" FieldSort : sorts




class FieldSort [[/blob/master/doc/entities/FieldSort.md]] {
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/FieldSort.md#field-string field]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/FieldSort.md#order-string order]]: <color:GRAY>String?</color>
  [[/blob/master/doc/entities/FieldSort.md#variable_order-boolean variableOrder]](): <color:GRAY>Boolean</color>
}




class DateHistogramAggregate [[/blob/master/doc/entities/DateHistogramAggregate.md]] {
  [[/blob/master/doc/entities/DateHistogramAggregate.md#format-string format]]: <color:GRAY>String?</color>
  [[/blob/master/doc/entities/DateHistogramAggregate.md#timezone-string timezone]]: <color:GRAY>String?</color>
  [[/blob/master/doc/entities/DateHistogramAggregate.md#min_doc_count-string min_doc_count]]: <color:GRAY>String?</color>
  [[/blob/master/doc/entities/DateHistogramAggregate.md#variable_min_doc_count-boolean variableMinDocCount]](): <color:GRAY>Boolean</color>
}

DateHistogramAggregate --|> ElasticsearchAggregate







DateHistogramAggregate *-- "1" DateHistogramInterval : interval






DateHistogramAggregate *-- "0..1" DateHistogramExtendedBounds : extended_bounds




class DateHistogramExtendedBounds [[/blob/master/doc/entities/DateHistogramExtendedBounds.md]] {
  [[/blob/master/doc/entities/DateHistogramExtendedBounds.md#min-string min]]: <color:GRAY>String?</color>
  [[/blob/master/doc/entities/DateHistogramExtendedBounds.md#max-string max]]: <color:GRAY>String?</color>
}




class DateHistogramInterval [[/blob/master/doc/entities/DateHistogramInterval.md]] {
  <color:RED><&flag></color><color:Green><&star></color>[[/blob/master/doc/entities/DateHistogramInterval.md#type-string type]]: <color:GRAY>String</color>
  <color:Green><&star></color>[[/blob/master/doc/entities/DateHistogramInterval.md#unit-string unit]]: <color:GRAY>String</color>
  <color:Green><&star></color>[[/blob/master/doc/entities/DateHistogramInterval.md#value-string value]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/DateHistogramInterval.md#variable_unit-boolean variableUnit]](): <color:GRAY>Boolean</color>
  [[/blob/master/doc/entities/DateHistogramInterval.md#variable_value-boolean variableValue]](): <color:GRAY>Boolean</color>
}




class DateHistogramCalendarInterval [[/blob/master/doc/entities/DateHistogramCalendarInterval.md]] {
  <color:GREEN><&arrow-thick-top></color><color:Green><&star></color>[[/blob/master/doc/entities/DateHistogramCalendarInterval.md#unit-string unit]]: <color:GRAY>String</color>
}

DateHistogramCalendarInterval --|> DateHistogramInterval





class DateHistogramFixedInterval [[/blob/master/doc/entities/DateHistogramFixedInterval.md]] {
  <color:GREEN><&arrow-thick-top></color><color:Green><&star></color>[[/blob/master/doc/entities/DateHistogramFixedInterval.md#unit-string unit]]: <color:GRAY>String</color>
  <color:GREEN><&arrow-thick-top></color><color:Green><&star></color>[[/blob/master/doc/entities/DateHistogramFixedInterval.md#value-string value]]: <color:GRAY>String</color>
}

DateHistogramFixedInterval --|> DateHistogramInterval





class DateRangeAggregate [[/blob/master/doc/entities/DateRangeAggregate.md]] {
  [[/blob/master/doc/entities/DateRangeAggregate.md#format-string format]]: <color:GRAY>String?</color>
}

DateRangeAggregate --|> ElasticsearchAggregate







DateRangeAggregate *-- "1..*" AggregateGroupRange : ranges




class AggregateGroupRange [[/blob/master/doc/entities/AggregateGroupRange.md]] {
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/AggregateGroupRange.md#key-string key]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/AggregateGroupRange.md#from-string from]]: <color:GRAY>String?</color>
  [[/blob/master/doc/entities/AggregateGroupRange.md#to-string to]]: <color:GRAY>String?</color>
}




class FilterAggregate [[/blob/master/doc/entities/FilterAggregate.md]] {
}

FilterAggregate --|> ElasticsearchAggregate






package laplacian.arch.api.service.elasticsearch {
  class ElasticsearchQueryPredicate {
  }
}


FilterAggregate *-- "1" ElasticsearchQueryPredicate : predicate




class FiltersAggregate [[/blob/master/doc/entities/FiltersAggregate.md]] {
}

FiltersAggregate --|> ElasticsearchAggregate







FiltersAggregate *-- "1..*" KeyedFilter : filters




class KeyedFilter [[/blob/master/doc/entities/KeyedFilter.md]] {
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/KeyedFilter.md#key-string key]]: <color:GRAY>String</color>
}





package laplacian.arch.api.service.elasticsearch {
  class ElasticsearchQueryPredicate {
  }
}


KeyedFilter *-- "1" ElasticsearchQueryPredicate : predicate




class SumAggregate [[/blob/master/doc/entities/SumAggregate.md]] {
}

SumAggregate --|> ElasticsearchAggregate





class AvgAggregate [[/blob/master/doc/entities/AvgAggregate.md]] {
}

AvgAggregate --|> ElasticsearchAggregate





class MinAggregate [[/blob/master/doc/entities/MinAggregate.md]] {
}

MinAggregate --|> ElasticsearchAggregate





class MaxAggregate [[/blob/master/doc/entities/MaxAggregate.md]] {
}

MaxAggregate --|> ElasticsearchAggregate





class ValueCountAggregate [[/blob/master/doc/entities/ValueCountAggregate.md]] {
}

ValueCountAggregate --|> ElasticsearchAggregate





class TermsAggregate [[/blob/master/doc/entities/TermsAggregate.md]] {
  [[/blob/master/doc/entities/TermsAggregate.md#max_buckets-string max_buckets]]: <color:GRAY>String?</color>
  [[/blob/master/doc/entities/TermsAggregate.md#variable_max_buckets-boolean variableMaxBuckets]](): <color:GRAY>Boolean</color>
  [[/blob/master/doc/entities/TermsAggregate.md#sort_by_count-string sort_by_count]]: <color:GRAY>String?</color>
  [[/blob/master/doc/entities/TermsAggregate.md#variable_order-boolean variableOrder]](): <color:GRAY>Boolean</color>
  [[/blob/master/doc/entities/TermsAggregate.md#shard_size-string shard_size]]: <color:GRAY>String?</color>
  [[/blob/master/doc/entities/TermsAggregate.md#variable_shard_size-boolean variableShardSize]](): <color:GRAY>Boolean</color>
  [[/blob/master/doc/entities/TermsAggregate.md#min_doc_count-string min_doc_count]]: <color:GRAY>String?</color>
  [[/blob/master/doc/entities/TermsAggregate.md#variable_min_doc_count-boolean variableMinDocCount]](): <color:GRAY>Boolean</color>
}

TermsAggregate --|> ElasticsearchAggregate





class ElasticsearchAggregate [[/blob/master/doc/entities/ElasticsearchAggregate.md]] {
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/ElasticsearchAggregate.md#name-string name]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/ElasticsearchAggregate.md#description-string description]]: <color:GRAY>String</color>
  <color:RED><&flag></color><color:Green><&star></color>[[/blob/master/doc/entities/ElasticsearchAggregate.md#aggregation_type-string aggregation_type]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/ElasticsearchAggregate.md#field-string field]]: <color:GRAY>String?</color>
}






ElasticsearchAggregate *-- "*" ElasticsearchAggregate : sub_aggregates




class ElasticsearchIndex [[/blob/master/doc/entities/ElasticsearchIndex.md]] {
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/ElasticsearchIndex.md#name-string name]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/ElasticsearchIndex.md#description-string description]]: <color:GRAY>String</color>
  <color:Green><&star></color>[[/blob/master/doc/entities/ElasticsearchIndex.md#document_model_name-string document_model_name]]: <color:GRAY>String</color>
}





package laplacian.metamodel {
  class Entity {
  }
}


ElasticsearchIndex -- "1" Entity : document_model






ElasticsearchIndex -- "*" ElasticsearchQuery : queries






ElasticsearchIndex *-- "*" ElasticsearchIndexSort : default_sorts




class ElasticsearchIndexSort [[/blob/master/doc/entities/ElasticsearchIndexSort.md]] {
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/ElasticsearchIndexSort.md#field-string field]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/ElasticsearchIndexSort.md#order-string order]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/ElasticsearchIndexSort.md#is_numeric-boolean is_numeric]]: <color:GRAY>Boolean?</color>
}




class ElasticsearchQueryPredicate [[/blob/master/doc/entities/ElasticsearchQueryPredicate.md]] {
  <color:RED><&key></color><color:RED><&flag></color><color:Green><&star></color>[[/blob/master/doc/entities/ElasticsearchQueryPredicate.md#type-string type]]: <color:GRAY>String</color>
}




class ElasticsearchQuerySort [[/blob/master/doc/entities/ElasticsearchQuerySort.md]] {
  <color:RED><&key></color><color:RED><&flag></color><color:Green><&star></color>[[/blob/master/doc/entities/ElasticsearchQuerySort.md#type-string type]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/ElasticsearchQuerySort.md#order-string order]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/ElasticsearchQuerySort.md#variable_order-boolean variableOrder]](): <color:GRAY>Boolean</color>
}




class ElasticsearchQueryScoreSort [[/blob/master/doc/entities/ElasticsearchQueryScoreSort.md]] {
}

ElasticsearchQueryScoreSort --|> ElasticsearchQuerySort





class ElasticsearchQueryFieldSort [[/blob/master/doc/entities/ElasticsearchQueryFieldSort.md]] {
  <color:Green><&star></color>[[/blob/master/doc/entities/ElasticsearchQueryFieldSort.md#name-string name]]: <color:GRAY>String</color>
}

ElasticsearchQueryFieldSort --|> ElasticsearchQuerySort





class ElasticsearchQuery [[/blob/master/doc/entities/ElasticsearchQuery.md]] {
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/ElasticsearchQuery.md#name-string name]]: <color:GRAY>String</color>
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/ElasticsearchQuery.md#index_name-string index_name]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/ElasticsearchQuery.md#description-string description]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/ElasticsearchQuery.md#page_size-string page_size]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/ElasticsearchQuery.md#variable_page_size-boolean variablePageSize]](): <color:GRAY>Boolean</color>
  [[/blob/master/doc/entities/ElasticsearchQuery.md#page_number-string page_number]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/ElasticsearchQuery.md#variable_page_number-boolean variablePageNumber]](): <color:GRAY>Boolean</color>
}






ElasticsearchQuery *-- "0..1" ElasticsearchQueryPredicate : predicate





package laplacian.arch.api.service {
  class ElasticsearchQuerySort {
  }
}


ElasticsearchQuery *-- "*" ElasticsearchQuerySort : sort





package laplacian.arch.api.service {
  class ElasticsearchAggregate {
  }
}


ElasticsearchQuery *-- "*" ElasticsearchAggregate : aggregates





package laplacian.arch.api.service {
  class ApiCallArgument {
  }
}


ElasticsearchQuery *-- "*" ApiCallArgument : parameters




class BoolQueryPredicate [[/blob/master/doc/entities/BoolQueryPredicate.md]] {
}

BoolQueryPredicate --|> ElasticsearchQueryPredicate







BoolQueryPredicate *-- "*" ElasticsearchQueryPredicate : must






BoolQueryPredicate *-- "*" ElasticsearchQueryPredicate : must_not






BoolQueryPredicate *-- "*" ElasticsearchQueryPredicate : should






BoolQueryPredicate *-- "*" ElasticsearchQueryPredicate : filter




class ExistsQueryPredicate [[/blob/master/doc/entities/ExistsQueryPredicate.md]] {
  <color:Green><&star></color>[[/blob/master/doc/entities/ExistsQueryPredicate.md#field-string field]]: <color:GRAY>String</color>
}

ExistsQueryPredicate --|> ElasticsearchQueryPredicate





class MatchAllQueryPredicate [[/blob/master/doc/entities/MatchAllQueryPredicate.md]] {
}

MatchAllQueryPredicate --|> ElasticsearchQueryPredicate





class MatchQueryPredicate [[/blob/master/doc/entities/MatchQueryPredicate.md]] {
  <color:Green><&star></color>[[/blob/master/doc/entities/MatchQueryPredicate.md#field-string field]]: <color:GRAY>String</color>
  <color:Green><&star></color>[[/blob/master/doc/entities/MatchQueryPredicate.md#value-string value]]: <color:GRAY>String</color>
}

MatchQueryPredicate --|> ElasticsearchQueryPredicate





class MultiMatchQueryPredicate [[/blob/master/doc/entities/MultiMatchQueryPredicate.md]] {
  <color:Green><&star></color>[[/blob/master/doc/entities/MultiMatchQueryPredicate.md#value-string value]]: <color:GRAY>String</color>
  <color:Green><&star></color>[[/blob/master/doc/entities/MultiMatchQueryPredicate.md#fields-listString fields]]: <color:GRAY>List<String></color>
}

MultiMatchQueryPredicate --|> ElasticsearchQueryPredicate





class QueryStringPredicate [[/blob/master/doc/entities/QueryStringPredicate.md]] {
  <color:Green><&star></color>[[/blob/master/doc/entities/QueryStringPredicate.md#query-string query]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/QueryStringPredicate.md#default_field-string default_field]]: <color:GRAY>String?</color>
  [[/blob/master/doc/entities/QueryStringPredicate.md#allow_leading_wildcard-boolean allow_leading_wildcard]]: <color:GRAY>Boolean?</color>
  [[/blob/master/doc/entities/QueryStringPredicate.md#analyze_wildcard-boolean analyze_wildcard]]: <color:GRAY>Boolean?</color>
  [[/blob/master/doc/entities/QueryStringPredicate.md#analyzer-string analyzer]]: <color:GRAY>String?</color>
  [[/blob/master/doc/entities/QueryStringPredicate.md#auto_generate_synonyms_phrase_query-boolean auto_generate_synonyms_phrase_query]]: <color:GRAY>Boolean?</color>
  [[/blob/master/doc/entities/QueryStringPredicate.md#boost-float boost]]: <color:GRAY>Float?</color>
  [[/blob/master/doc/entities/QueryStringPredicate.md#default_operator-string default_operator]]: <color:GRAY>String?</color>
  [[/blob/master/doc/entities/QueryStringPredicate.md#enable_position_increments-boolean enable_position_increments]]: <color:GRAY>Boolean?</color>
  [[/blob/master/doc/entities/QueryStringPredicate.md#fields-listString fields]]: <color:GRAY>List<String></color>
  [[/blob/master/doc/entities/QueryStringPredicate.md#fuzziness-string fuzziness]]: <color:GRAY>String?</color>
  [[/blob/master/doc/entities/QueryStringPredicate.md#fuzzy_max_expansion-int fuzzy_max_expansion]]: <color:GRAY>Int?</color>
  [[/blob/master/doc/entities/QueryStringPredicate.md#fuzzy_prefix_length-int fuzzy_prefix_length]]: <color:GRAY>Int?</color>
  [[/blob/master/doc/entities/QueryStringPredicate.md#fuzzy_transpositions-boolean fuzzy_transpositions]]: <color:GRAY>Boolean?</color>
  [[/blob/master/doc/entities/QueryStringPredicate.md#lenient-boolean lenient]]: <color:GRAY>Boolean?</color>
  [[/blob/master/doc/entities/QueryStringPredicate.md#max_determinized_states-int max_determinized_states]]: <color:GRAY>Int?</color>
  [[/blob/master/doc/entities/QueryStringPredicate.md#minimum_should_match-string minimum_should_match]]: <color:GRAY>String?</color>
  [[/blob/master/doc/entities/QueryStringPredicate.md#quote_analyzer-string quote_analyzer]]: <color:GRAY>String?</color>
  [[/blob/master/doc/entities/QueryStringPredicate.md#phrase_slop-int phrase_slop]]: <color:GRAY>Int?</color>
  [[/blob/master/doc/entities/QueryStringPredicate.md#quote_field_suffix-string quote_field_suffix]]: <color:GRAY>String?</color>
  [[/blob/master/doc/entities/QueryStringPredicate.md#rewrite-string rewrite]]: <color:GRAY>String?</color>
  [[/blob/master/doc/entities/QueryStringPredicate.md#time_zone-string time_zone]]: <color:GRAY>String?</color>
}

QueryStringPredicate --|> ElasticsearchQueryPredicate





class RangeQueryPredicate [[/blob/master/doc/entities/RangeQueryPredicate.md]] {
  <color:Green><&star></color>[[/blob/master/doc/entities/RangeQueryPredicate.md#field-string field]]: <color:GRAY>String</color>
  <color:Green><&star></color>[[/blob/master/doc/entities/RangeQueryPredicate.md#from-string from]]: <color:GRAY>String</color>
  <color:Green><&star></color>[[/blob/master/doc/entities/RangeQueryPredicate.md#to-string to]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/RangeQueryPredicate.md#include_lower-boolean include_lower]]: <color:GRAY>Boolean?</color>
  [[/blob/master/doc/entities/RangeQueryPredicate.md#include_upper-boolean include_upper]]: <color:GRAY>Boolean?</color>
  [[/blob/master/doc/entities/RangeQueryPredicate.md#timezone-string timezone]]: <color:GRAY>String?</color>
}

RangeQueryPredicate --|> ElasticsearchQueryPredicate





class TermQueryPredicate [[/blob/master/doc/entities/TermQueryPredicate.md]] {
  <color:Green><&star></color>[[/blob/master/doc/entities/TermQueryPredicate.md#field-string field]]: <color:GRAY>String</color>
  <color:Green><&star></color>[[/blob/master/doc/entities/TermQueryPredicate.md#value-string value]]: <color:GRAY>String</color>
  <color:Green><&star></color>[[/blob/master/doc/entities/TermQueryPredicate.md#boost-int boost]]: <color:GRAY>Int</color>
}

TermQueryPredicate --|> ElasticsearchQueryPredicate





class TermsQueryPredicate [[/blob/master/doc/entities/TermsQueryPredicate.md]] {
  <color:Green><&star></color>[[/blob/master/doc/entities/TermsQueryPredicate.md#field-string field]]: <color:GRAY>String</color>
  <color:Green><&star></color>[[/blob/master/doc/entities/TermsQueryPredicate.md#value-string value]]: <color:GRAY>String</color>
  <color:Green><&star></color>[[/blob/master/doc/entities/TermsQueryPredicate.md#boost-int boost]]: <color:GRAY>Int</color>
}

TermsQueryPredicate --|> ElasticsearchQueryPredicate





class EntityOnDatabase [[/blob/master/doc/entities/EntityOnDatabase.md]] {
  <color:Green><&star></color>[[/blob/master/doc/entities/EntityOnDatabase.md#entity_name-string entity_name]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/EntityOnDatabase.md#datasource_name-string datasource_name]]: <color:GRAY>String</color>
}

EntityOnDatabase --|> GraphqlType






package laplacian.metamodel {
  class Entity {
  }
}


EntityOnDatabase -- "1" Entity : entity




class ExternalRestResource [[/blob/master/doc/entities/ExternalRestResource.md]] {
  <color:Green><&star></color>[[/blob/master/doc/entities/ExternalRestResource.md#rest_resource_name-string rest_resource_name]]: <color:GRAY>String</color>
  <color:Green><&star></color>[[/blob/master/doc/entities/ExternalRestResource.md#rest_client_name-string rest_client_name]]: <color:GRAY>String</color>
}

ExternalRestResource --|> GraphqlType






package laplacian.arch.api.service {
  class RestResource {
  }
}


ExternalRestResource -- "1" RestResource : rest_resource





package laplacian.arch.api.service {
  class RestClient {
  }
}


ExternalRestResource -- "1" RestClient : rest_client




class IndexedDocument [[/blob/master/doc/entities/IndexedDocument.md]] {
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/IndexedDocument.md#index_name-string index_name]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/IndexedDocument.md#search_engine_client_name-string search_engine_client_name]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/IndexedDocument.md#default_searcher_name-string default_searcher_name]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/IndexedDocument.md#document_model-entity documentModel]](): <color:GRAY>Entity</color>
}

IndexedDocument --|> GraphqlType






package laplacian.arch.api.service.elasticsearch {
  class ElasticsearchIndex {
  }
}


IndexedDocument -- "1" ElasticsearchIndex : elasticsearch_index




class RestOperation [[/blob/master/doc/entities/RestOperation.md]] {
  <color:Green><&star></color>[[/blob/master/doc/entities/RestOperation.md#method-string method]]: <color:GRAY>String</color>
  <color:Green><&star></color>[[/blob/master/doc/entities/RestOperation.md#path-string path]]: <color:GRAY>String</color>
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/RestOperation.md#name-string name]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/RestOperation.md#description-string description]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/RestOperation.md#response_model_name-string response_model_name]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/RestOperation.md#cache_policy_name-string cache_policy_name]]: <color:GRAY>String?</color>
  [[/blob/master/doc/entities/RestOperation.md#effective_cache_policy-cachePolicy effectiveCachePolicy]](): <color:GRAY>CachePolicy?</color>
}






RestOperation *-- "*" ApiCallArgument : arguments






RestOperation *-- "*" RestRequestParameter : path_parameters






RestOperation *-- "*" RestRequestParameter : query_parameters






RestOperation *-- "*" RestRequestParameter : http_headers





package laplacian.metamodel {
  class Entity {
  }
}


RestOperation -- "1" Entity : response_model





package laplacian.arch.api.service.cache {
  class CachePolicy {
  }
}


RestOperation -- "0..1" CachePolicy : cache_policy




class RestRequestParameter [[/blob/master/doc/entities/RestRequestParameter.md]] {
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/RestRequestParameter.md#name-string name]]: <color:GRAY>String</color>
  <color:Green><&star></color>[[/blob/master/doc/entities/RestRequestParameter.md#type-string type]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/RestRequestParameter.md#multiple-boolean multiple]]: <color:GRAY>Boolean</color>
  <color:Green><&star></color>[[/blob/master/doc/entities/RestRequestParameter.md#value-string value]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/RestRequestParameter.md#variable-boolean variable]](): <color:GRAY>Boolean</color>
}




class RestResource [[/blob/master/doc/entities/RestResource.md]] {
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/RestResource.md#name-string name]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/RestResource.md#description-string description]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/RestResource.md#resource_model_name-string resource_model_name]]: <color:GRAY>String?</color>
  <color:Green><&star></color>[[/blob/master/doc/entities/RestResource.md#base_url-string base_url]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/RestResource.md#cache_policy_name-string cache_policy_name]]: <color:GRAY>String?</color>
  [[/blob/master/doc/entities/RestResource.md#enable_automatic_cookie_handling-boolean enable_automatic_cookie_handling]]: <color:GRAY>Boolean</color>
}






RestResource *-- "1..*" RestOperation : operations






RestResource *-- "*" ConfigurationBinding : configurations





package laplacian.arch.api.service.cache {
  class CachePolicy {
  }
}


RestResource -- "0..1" CachePolicy : cache_policy




class Service [[/blob/master/doc/entities/Service.md]] {
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/Service.md#name-string name]]: <color:GRAY>String</color>
  <color:Green><&star></color>[[/blob/master/doc/entities/Service.md#version-string version]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/Service.md#namespace-string namespace]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/Service.md#description-string description]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/Service.md#depends_on_elasticsearch-boolean dependsOnElasticsearch]](): <color:GRAY>Boolean</color>
  [[/blob/master/doc/entities/Service.md#depends_on_cache-boolean dependsOnCache]](): <color:GRAY>Boolean</color>
  [[/blob/master/doc/entities/Service.md#depends_on_redis_cache-boolean dependsOnRedisCache]](): <color:GRAY>Boolean</color>
  [[/blob/master/doc/entities/Service.md#default_datasource-datasource defaultDatasource]](): <color:GRAY>Datasource?</color>
  [[/blob/master/doc/entities/Service.md#graphql_types-listGraphqlType graphqlTypes]](): <color:GRAY>List<GraphqlType></color>
  [[/blob/master/doc/entities/Service.md#entities_used_in_graphql-listEntity entitiesUsedInGraphql]](): <color:GRAY>List<Entity></color>
  [[/blob/master/doc/entities/Service.md#top_level_entities_used_in_graphql-listEntity topLevelEntitiesUsedInGraphql]](): <color:GRAY>List<Entity></color>
  [[/blob/master/doc/entities/Service.md#graphql_types_backed_by_database_table-listEntityOnDatabase graphqlTypesBackedByDatabaseTable]](): <color:GRAY>List<EntityOnDatabase></color>
  [[/blob/master/doc/entities/Service.md#entities_backing_graphql_type-listEntity entitiesBackingGraphqlType]](): <color:GRAY>List<Entity></color>
  [[/blob/master/doc/entities/Service.md#top_level_entities_backing_graphql_type-listEntity topLevelEntitiesBackingGraphqlType]](): <color:GRAY>List<Entity></color>
  [[/blob/master/doc/entities/Service.md#graphql_types_backed_by_external_rest_resource-listExternalRestResource graphqlTypesBackedByExternalRestResource]](): <color:GRAY>List<ExternalRestResource></color>
  [[/blob/master/doc/entities/Service.md#rest_resources_backing_graphql_type-listRestResource restResourcesBackingGraphqlType]](): <color:GRAY>List<RestResource></color>
  [[/blob/master/doc/entities/Service.md#graphql_types_backed_by_indexed_document-listIndexedDocument graphqlTypesBackedByIndexedDocument]](): <color:GRAY>List<IndexedDocument></color>
  [[/blob/master/doc/entities/Service.md#elasticsearch_indexes-listElasticsearchIndex elasticsearchIndexes]](): <color:GRAY>List<ElasticsearchIndex></color>
  [[/blob/master/doc/entities/Service.md#graphql_type_relationships-listGraphqlTypeRelationship graphqlTypeRelationships]](): <color:GRAY>List<GraphqlTypeRelationship></color>
  [[/blob/master/doc/entities/Service.md#cache_policies-listCachePolicy cachePolicies]](): <color:GRAY>List<CachePolicy></color>
}






Service *-- "*" Datasource : datasources






Service *-- "*" GraphqlTypeEntry : graphql_type_entries






Service *-- "*" RestClient : rest_clients






Service *-- "*" ElasticSearchClient : elastic_search_clients






Service *-- "*" ServiceConfigurationCategory : configuration_categories




class Datasource [[/blob/master/doc/entities/Datasource.md]] {
  <color:RED><&key></color>[[/blob/master/doc/entities/Datasource.md#name-string name]]: <color:GRAY>String</color>
  <color:Green><&star></color>[[/blob/master/doc/entities/Datasource.md#type-string type]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/Datasource.md#description-string description]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/Datasource.md#entities-listEntity entities]](): <color:GRAY>List<Entity></color>
  [[/blob/master/doc/entities/Datasource.md#top_level_entities-listEntity topLevelEntities]](): <color:GRAY>List<Entity></color>
}




class ElasticSearchClient [[/blob/master/doc/entities/ElasticSearchClient.md]] {
  <color:Green><&star></color>[[/blob/master/doc/entities/ElasticSearchClient.md#name-string name]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/ElasticSearchClient.md#is_default-boolean is_default]]: <color:GRAY>Boolean</color>
  [[/blob/master/doc/entities/ElasticSearchClient.md#configuration_category-string configuration_category]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/ElasticSearchClient.md#configuration_name_of_endpoints-string configuration_name_of_endpoints]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/ElasticSearchClient.md#configuration_name_of_path_prefix-string configuration_name_of_path_prefix]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/ElasticSearchClient.md#configuration_name_of_connect_timeout-string configuration_name_of_connect_timeout]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/ElasticSearchClient.md#configuration_name_of_socket_timeout-string configuration_name_of_socket_timeout]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/ElasticSearchClient.md#configuration_name_of_max_in_memory_size-string configuration_name_of_max_in_memory_size]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/ElasticSearchClient.md#configurations-listServiceConfiguration configurations]](): <color:GRAY>List<ServiceConfiguration></color>
}






ElasticSearchClient -- "1" ServiceConfiguration : endpoints






ElasticSearchClient -- "0..1" ServiceConfiguration : path_prefix






ElasticSearchClient -- "0..1" ServiceConfiguration : connect_timeout






ElasticSearchClient -- "0..1" ServiceConfiguration : socket_timeout






ElasticSearchClient -- "0..1" ServiceConfiguration : max_in_memory_size




class GraphqlType [[/blob/master/doc/entities/GraphqlType.md]] {
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/GraphqlType.md#name-string name]]: <color:GRAY>String</color>
  <color:RED><&flag></color><color:Green><&star></color>[[/blob/master/doc/entities/GraphqlType.md#resolver_type-string resolver_type]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/GraphqlType.md#description-string description]]: <color:GRAY>String</color>
}






GraphqlType *-- "*" GraphqlTypeRelationship : relationships




class GraphqlTypeEntry [[/blob/master/doc/entities/GraphqlTypeEntry.md]] {
  <color:Green><&star></color>[[/blob/master/doc/entities/GraphqlTypeEntry.md#name-string name]]: <color:GRAY>String</color>
}





package laplacian.arch.api.service.graphql {
  class GraphqlType {
  }
}


GraphqlTypeEntry -- "1" GraphqlType : graphql_type




class GraphqlTypeRelationship [[/blob/master/doc/entities/GraphqlTypeRelationship.md]] {
  <color:Green><&star></color>[[/blob/master/doc/entities/GraphqlTypeRelationship.md#name-string name]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/GraphqlTypeRelationship.md#description-string description]]: <color:GRAY>String</color>
  <color:RED><&flag></color><color:Green><&star></color>[[/blob/master/doc/entities/GraphqlTypeRelationship.md#type-string type]]: <color:GRAY>String</color>
  <color:Green><&star></color>[[/blob/master/doc/entities/GraphqlTypeRelationship.md#referencing_graphql_type_name-string referencing_graphql_type_name]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/GraphqlTypeRelationship.md#multiple-boolean multiple]]: <color:GRAY>Boolean</color>
  [[/blob/master/doc/entities/GraphqlTypeRelationship.md#nullable-boolean nullable]]: <color:GRAY>Boolean</color>
}






GraphqlTypeRelationship -- "1" GraphqlType : referencing_graphql_type




class GraphqlIndexedDocumentRelationship [[/blob/master/doc/entities/GraphqlIndexedDocumentRelationship.md]] {
  [[/blob/master/doc/entities/GraphqlIndexedDocumentRelationship.md#field_type_name-string fieldTypeName]](): <color:GRAY>String</color>
  [[/blob/master/doc/entities/GraphqlIndexedDocumentRelationship.md#resolver_name-string resolverName]](): <color:GRAY>String</color>
}

GraphqlIndexedDocumentRelationship --|> GraphqlTypeRelationship






package laplacian.arch.api.service.graphql_type {
  class GraphqlTypeRelationshipFieldMapping {
  }
}


GraphqlIndexedDocumentRelationship *-- "1..*" GraphqlTypeRelationshipFieldMapping : field_mappings




class GraphqlTypeRelationshipFieldMapping [[/blob/master/doc/entities/GraphqlTypeRelationshipFieldMapping.md]] {
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/GraphqlTypeRelationshipFieldMapping.md#from-string from]]: <color:GRAY>String</color>
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/GraphqlTypeRelationshipFieldMapping.md#to-string to]]: <color:GRAY>String</color>
}




class RestClient [[/blob/master/doc/entities/RestClient.md]] {
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/RestClient.md#name-string name]]: <color:GRAY>String</color>
}




class ServiceConfiguration [[/blob/master/doc/entities/ServiceConfiguration.md]] {
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/ServiceConfiguration.md#name-string name]]: <color:GRAY>String</color>
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/ServiceConfiguration.md#category-string category]]: <color:GRAY>String</color>
  <color:Green><&star></color>[[/blob/master/doc/entities/ServiceConfiguration.md#type-string type]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/ServiceConfiguration.md#key-string key]](): <color:GRAY>String</color>
  [[/blob/master/doc/entities/ServiceConfiguration.md#default_value-string default_value]]: <color:GRAY>String?</color>
  [[/blob/master/doc/entities/ServiceConfiguration.md#environment_variable_name-string environment_variable_name]]: <color:GRAY>String</color>
}




class ServiceConfigurationCategory [[/blob/master/doc/entities/ServiceConfigurationCategory.md]] {
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/ServiceConfigurationCategory.md#name-string name]]: <color:GRAY>String</color>
}






ServiceConfigurationCategory -- "*" ServiceConfiguration : configurations




class ConfigurationBinding [[/blob/master/doc/entities/ConfigurationBinding.md]] {
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/ConfigurationBinding.md#name-string name]]: <color:GRAY>String</color>
  <color:RED><&key></color><color:Green><&star></color>[[/blob/master/doc/entities/ConfigurationBinding.md#category-string category]]: <color:GRAY>String</color>
  [[/blob/master/doc/entities/ConfigurationBinding.md#variable_name-string variable_name]]: <color:GRAY>String</color>
}






ConfigurationBinding -- "1" ServiceConfiguration : definition



@enduml