entities:
- name: service
  namespace: laplacian.arch.api.service
  properties:
  - name: name
    type: string
    primary_key: true

  - name: version
    type: string

  - name: namespace
    type: string
    domain_type_name: namespace
    optional: true
    default_value: |
      "${_context.get("project.namespace")}.service.${name.lowerUnderscorize()}"

  - name: description
    type: string
    optional: true
    default_value: |
      name

  - name: depends_on_elasticsearch
    type: boolean
    snippet: |
      elasticsearchIndexes.isNotEmpty()

  - name: depends_on_cache
    type: boolean
    snippet: |
      cachePolicies.isNotEmpty()

  - name: depends_on_redis_cache
    type: boolean
    snippet: |
      redisCachePolicies.isNotEmpty()

  - name: depends_on_mybatis
    type: boolean
    snippet: |
      mybatisFetchers.isNotEmpty()

  - name: depends_on_postgres_jdbc
    type: boolean
    snippet: |
      datasources.any { it.type == "postgres_jdbc" }

  - name: depends_on_oracle_jdbc
    type: boolean
    snippet: |
      datasources.any { it.type == "oracle_jdbc" }

  relationships:
  - name: datasource_entries
    cardinality: '*'
    reference_entity_name: datasource_entry
    reference_entity_namespace: laplacian.arch.api.service.datasource
    aggregate: true

  - name: datasources
    cardinality: '*'
    reference_entity_name: datasource
    reference_entity_namespace: laplacian.arch.api.service.datasource
    snippet: |
      datasourceEntries.map{ it.datasource }

  - name: graphql_type_entries
    cardinality: '*'
    reference_entity_name: graphql_type_entry
    aggregate: true

  - name: graphql_types
    cardinality: '*'
    reference_entity_name: graphql_type
    reference_entity_namespace: laplacian.arch.api.service.graphql
    snippet: |
      graphqlTypeEntries.map{ it.graphqlType }.distinct()

  - name: elasticsearch_indexes
    reference_entity_name: elasticsearch_index
    reference_entity_namespace: laplacian.arch.api.service.elasticsearch
    cardinality: '*'
    snippet: |
      listOf<ElasticsearchIndex>()

  - name: configuration_categories
    reference_entity_name: service_configuration_category
    cardinality: '*'
    aggregate: true

  - name: graphql_fields
    reference_entity_name: graphql_field
    reference_entity_namespace: laplacian.arch.api.service.graphql
    cardinality: '*'
    snippet: |
      graphqlTypes
      .flatMap{ it.fields ?: emptyList() }

  - name: graphql_field_fetchers
    reference_entity_name: graphql_field_fetcher
    reference_entity_namespace: laplacian.arch.api.service.graphql
    cardinality: '*'
    snippet: |
      graphqlFields.map{ it.fetcher }.filterNotNull()

  - name: mybatis_fetchers
    reference_entity_name: mybatis_fetcher
    reference_entity_namespace: laplacian.arch.api.service.mybatis
    cardinality: '*'
    snippet: |
      graphqlFieldFetchers.filterIsInstance<MybatisFetcher>()

  - name: cache_policies
    reference_entity_name: cache_policy
    reference_entity_namespace: laplacian.arch.api.service.cache
    cardinality: '*'
    snippet: |
      graphqlFieldFetchers.map{ it.cachePolicy }.filterNotNull()

  - name: redis_cache_policies
    reference_entity_name: redis_cache_policy
    reference_entity_namespace: laplacian.arch.api.service.cache
    cardinality: '*'
    snippet: |
      cachePolicies.filterIsInstance<RedisCachePolicy>()

