entities:
- name: service
  namespace: laplacian.arch.api.service
  properties:
  - name: name
    type: string
    primary_key: true

  - name: version
    type: string

  - name: namespace
    type: string
    domain_type_name: namespace
    optional: true
    default_value: |
      "${_context.get("project.namespace")}.service.${name.lowerUnderscorize()}"

  - name: description
    type: string
    optional: true
    default_value: |
      name

  - name: depends_on_elasticsearch
    type: boolean
    snippet: |
      elasticsearchIndexes.isNotEmpty()

  - name: depends_on_cache
    type: boolean
    snippet: |
      restResourcesBackingGraphqlType.any {
          it.cachePolicy != null || it.operations.any{ it.cachePolicy != null }
      }

  - name: depends_on_redis_cache
    type: boolean
    snippet: |
      restResourcesBackingGraphqlType.any {
          it.cachePolicy?.storeType == "redis" ?: false ||
          it.operations.any{ it.cachePolicy?.storeType == "redis" ?: false }
      }

  relationships:
  - name: datasources
    cardinality: '*'
    reference_entity_name: datasource
    aggregate: true

  - name: default_datasource
    cardinality: '0..1'
    reference_entity_name: datasource
    snippet: |
      datasources
      .find{ it.name == "default" }

  - name: graphql_type_entries
    cardinality: '*'
    reference_entity_name: graphql_type_entry
    aggregate: true

  - name: graphql_types
    cardinality: '*'
    reference_entity_name: graphql_type
    snippet: |
      graphqlTypeEntries.map{ it.graphqlType }.distinct()

  - name: entities_used_in_graphql
    cardinality: '*'
    reference_entity_name: entity
    snippet: |
      graphqlTypes
        .map{ if (it is EntityOnDatabase) it.entity else null }
        .filterNotNull()
        .distinct()

  - name: top_level_entities_used_in_graphql
    cardinality: '*'
    reference_entity_name: entity
    snippet: |
      entitiesUsedInGraphql.filter{ it.topLevel }

  - name: graphql_types_backed_by_database_table
    cardinality: '*'
    reference_entity_name: entity_on_database
    snippet: |
      graphqlTypes.map{ it as? EntityOnDatabase }.filterNotNull()

  - name: entities_backing_graphql_type
    cardinality: '*'
    reference_entity_name: entity
    snippet: |
      graphqlTypesBackedByDatabaseTable
      .map{ it.entity }
      .distinct()

  - name: top_level_entities_backing_graphql_type
    cardinality: '*'
    reference_entity_name: entity
    snippet: |
      entitiesBackingGraphqlType
      .filter{ it.topLevel }

  - name: graphql_types_backed_by_external_rest_resource
    cardinality: '*'
    reference_entity_name: external_rest_resource
    snippet: |
      graphqlTypes.map{ it as? ExternalRestResource }.filterNotNull()

  - name: rest_resources_backing_graphql_type
    cardinality: '*'
    reference_entity_name: rest_resource
    snippet: |
      graphqlTypesBackedByExternalRestResource
      .map{ it.restResource }
      .distinct()

  - name: graphql_types_backed_by_indexed_document
    cardinality: '*'
    reference_entity_name: indexed_document
    snippet: |
      graphqlTypes.map{ it as? IndexedDocument }.filterNotNull()

  - name: rest_clients
    reference_entity_name: rest_client
    cardinality: '*'
    aggregate: true

  - name: elastic_search_clients
    reference_entity_name: elastic_search_client
    cardinality: '*'
    aggregate: true

  - name: elasticsearch_indexes
    reference_entity_name: elasticsearch_index
    cardinality: '*'
    snippet: |
      graphqlTypesBackedByIndexedDocument.map{ it.elasticsearchIndex }
      .distinct()

  - name: graphql_type_relationships
    reference_entity_name: graphql_type_relationship
    cardinality: '*'
    snippet: |
      graphqlTypes.map{ it.relationships }.flatten().distinct()

  - name: configuration_categories
    reference_entity_name: service_configuration_category
    cardinality: '*'
    aggregate: true

  - name: cache_policies
    reference_entity_name: cache_policy
    cardinality: '*'
    snippet: |
      (
          restResourcesBackingGraphqlType.map{ it.cachePolicy } +
          restResourcesBackingGraphqlType.flatMap{ it.operations.map{ it.cachePolicy }}
      )
      .filterNotNull()
      .distinct()
