project:
  sources:
  - "README.md"
  - "doc/entities/DataAccess.md"
  - "doc/entities/Datasource.md"
  - "doc/entities/EntityReference.md"
  - "doc/entities/GraphqlQuery.md"
  - "doc/entities/ResourceEntry.md"
  - "doc/entities/RestDataItem.md"
  - "doc/entities/RestOperation.md"
  - "doc/entities/RestResource.md"
  - "doc/entities/Service.md"
  - "doc/image/model-diagram.svg"
  - ".editorconfig"
  - ".gitattributes"
  - ".gitignore"
  - "model/project/scripts/generate.yaml"
  - "model/project/scripts/publish-local.yaml"
  - "model/project/sources.yaml"
  - "model/project.yaml"
  - "src/entities/graphql_query.yml"
  - "src/entities/rest_data_item.yml"
  - "src/entities/rest_operation.yml"
  - "src/entities/rest_resource.yml"
  - "src/entities/service/resource_entry.yaml"
  - "src/entities/service.yml"
  - "src/value_domain_types/http_method_for_rest.yaml"
  - "src/value_domain_types/url_path_with_placeholders.yaml"
