entities:
- name: service
  namespace: laplacian.arch.api.service
  properties:
  - name: name
    type: string

  - name: identifier
    type: string
    domain_type_name: identifier
    optional: true
    default_value: |
      name.lowerUnderscorize()

  - name: version
    type: string

  - name: api_version
    type: string
    optional: true
    default_value: |
      "v1"

  - name: endpoint
    type: string
    optional: true
    default_value: |
      "${protocol}://${host}:${port}${path}/${apiVersion}"

  - name: host
    type: string
    optional: true
    default_value: |
      "identifier.lowerHyphenize()"

  - name: port
    type: number
    optional: true
    default_value: |
      8080

  - name: protocol
    type: string
    domain:
      choices:
      - value: http
      - value: https
    optional: true
    default_value: |
      "http"

  - name: path
    type: string
    optional: true
    default_value: |
      "/${identifier.lowerHyphenize()}"

  - name: namespace
    type: string
    domain_type_name: namespace
    optional: true
    default_value: |
      "${_context.get("project.namespace")}.service.$identifier"

  - name: description
    type: string
    optional: true
    default_value: |
      name

  - name: datasource_name
    type: string

  relationships:
  - name: resource_entries
    cardinality: '*'
    reference_entity_name: resource_entry
    aggregate: true

  - name: resources
    cardinality: '*'
    reference_entity_name: rest_resource
    snippet: |
      resourceEntries.map{ it.resource }

  - name: datasource
    cardinality: '1'
    reference_entity_name: datasource
    mappings:
    - from: datasource_name
      to: name

  - name: relating_entities
    cardinality: '*'
    reference_entity_name: entity
    snippet: |
      resources
      .flatMap{ it.relatingEntities }
      .distinctBy{ it.fqn }

  - name: relating_top_level_entities
    cardinality: '*'
    reference_entity_name: entity
    snippet: |
      relatingEntities
      .filter{ it.topLevel }

  - name: graphql_queries
    cardinality: '*'
    reference_entity_name: graphql_query
    aggregate: true

