project:
  group: laplacian-arch
  name: service-api.domain-model-plugin
  type: domain-model-plugin
  namespace: laplacian.arch.service.api
  version: '1.0.0'
  description:
    en: |
      A domain model plugin module for the service-api.domain-model.
    ja: |
      service-api.domain-model のドメインモデルプラグインモジュール
    zh: |
      service-api.domain-model 域模型插件模块
  module_repositories:
    local:
      ../../../../../mvn-repo
    remote:
    - https://github.com/nabla-squared/mvn-repo
  plugins:
  - group: laplacian-arch
    name: datasource.domain-model-plugin
    version: '1.0.0'
  models:
  - group: laplacian-arch
    name: service-api.domain-model
    version: '1.0.0'
  - group: laplacian-arch
    name: datasource.domain-model
    version: '1.0.0'
